name: deploy
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    steps:
      - run: echo deploy

  stg:
    runs-on: ubuntu-latest
    needs: build
    environment: stg
    steps:
      - run: echo stg


  prd:
    runs-on: ubuntu-latest
    needs: build
    environment: prd
    steps:
      - run: echo prd
